### ISSUE TITLE
Apps are started in compatibility mode on iPad Pro 11" devices

### ISSUE THREAD

**Issue by sbmars** [trigger-corp/forge#1]
**Device information:**
 - Hardware: iPad pro 11"
 - Operating System and Version: iOS 12
 - Forge Platform version: v.2.7.5

**App information:**

  "platform_version": "v.2.7.5",
  "core": {
    ...
    "ios": {
      "device_family": "any",
      "package_name": "%ios_package_name%",
      "disable_web_storage_backup": true,
      "adjust_content_insets": "never",
      "webview": "WKWebView"
    }
  },

**To Reproduce**

1. Open the app
2. The insets are wrong 

**Expected behaviour**
 
We have different styling for iPad and iPhone devices. iPhone should use the iPhone style and iPads the iPad style.

**Actual behaviour**

But as the new iOS device is not identified correctly, it will be rendered with the iPhone styling streched to the full screen.

**Related information:**

![8ce4e632-e214-4485-af54-2ad494728c08 1](https://user-images.githubusercontent.com/46187741/51892680-f72b6080-23a2-11e9-8074-aaa8d306c7c7.JPG)

**Comment by antoinevg** [comment]
This isn't caused by a device identification or display scaling issue but rather by iOS running the app in "compatibility mode" on an iPad Pro 11".

Recompiling the app on Xcode 10.1 & linking against the iOS 12.1 SDK seems to sort it out.

We're still not ready to push Xcode 10.1 to production but, in the meantime, you can use the staging release: [v2.7.6](https://trigger.io/docs/current/api/release_notes.html)

If you haven't already, you may also need to update to Xcode 10.1 on your side.

/spend 3h

**Comment by sbmars** [comment]
@antoinevg are there any news regarding pushing Xcode 10.1 to production? Because of we receiving comments vom apple:
"SDK Version Issue - This app was built with the iOS 12.0 SDK. Starting March 2019, all iOS apps submitted to the App Store must be built with the iOS 12.1 SDK or later, included in Xcode 10.1 or later."

**Comment by antoinevg** [comment]
We just released platform `v2.7.6` to production this morning :-)

https://trigger.io/docs/current/api/release_notes.html
