### ISSUE TITLE
Apps freezing on launch screen when used with on-demand VPN (iOS)

### ISSUE THREAD

**Issue by ice8lue** [trigger-corp/forge#27]
**Device information:**
 - Hardware: iPhone 7, 8, X, XS
 - Operating System and Version: iOS 12.4, 13.1
 - Forge Platform version: v2.7.6

**App information:**
Active modules:

contact v2.12
icons v2.9
launchimage v2.13
display v2.11
file v2.23
capture v2.0
notification v2.8
bolts v1.6
urlhandler v2.1
request v2.11
parse v3.0 (?)
share v1.2
tabs v2.23 
httpd v1.4
prefs v2.2
browsersettings v1.6
platform v2.3

**To Reproduce**
One of our customers is using VMWare Workspace One MDM and VPN to distribute the app. They have an on-demand VPN set up which connects and disconnects automatically with the app starting up and shutting down. When both, the app and the VPN start up, the app freezes on launch screen.

1. Define a VPN on-demand profile
2. Start app --> Freeze
3. Force close app and directly re-start it (so VPN is still active) --> App starts fine

**Expected behaviour**
App starts as usual.

**Actual behaviour**
App freezes.

**Related information:**
We did some debugging already and the freeze occurs during native start up, before modules are initialized. No WebView initialized at that point. There is no app error thrown but we get logs from the VMWare stuff about failed proxy connections. Another customer is using MobileIron with a similar setup and symptoms.

It looks like at that point, iOS says it's online but no connection can be created. Maybe there is some call failing unhandled or needs a retry?

**Comment by prud** [comment]
@ice8lue Any idea if something has changed here with iOS 13 and the new Trigger.io platform?

**Comment by antoinevg** [comment]
**Root cause:**

* On iOS 12 the embedded webserver on the localhost interface is not accessible to the Forge runtime when the VPN starts up. This was because their VPN and/or iOS 12 was configured to re-route requests made to the device's loopback interface.
* As of iOS 13 this, for unknown reasons, doesn't happen and the app starts up just fine the first time. 
* On both iOS 12 & iOS 13 the VPN interface would prevent the embedded webserver from binding to the device's loopback interface after the app had been backgrounded and then foregrounded again. (This is why the app appeared to work when starting it up a second time because, on failure of httpd, it falls back to loading the app's index.html from the local filesystem.)

**Resolution:**

* Update apps to Forge platform v2.8.5 which provides:
    * iOS 12 workaround for VPN interface preventing the webserver from binding to localhost.
    * iOS 13 workaround for VPN interface preventing the webserver from binding to localhost.
* Two new requirements for enterprise deployments of Trigger.IO Forge apps:
    1. Add localhost and 127.0.0.1 to the exclusion list of any web proxy configurations provisioned to the app and/or device.
    2. Add localhost and 127.0.0.1 to the exclusion list of any VPN tunnels provisioned to the app and/or device.

**Comment by prud** [comment]
Fantastic, thanks so far @antoinevg - sounds great!

Can you share some rough intel on what has been touched for those workarounds to prevent the binding? We want to make sure to properly have regression testing for other types of connections of course 🙏

**Comment by antoinevg** [comment]
I had to patch the socket library (https://github.com/robbiehanson/CocoaAsyncSocket) the embedded web server library (https://github.com/thecatalinstan/Criollo) depends on to detect and exclude VPN interfaces when creating new listen sockets. Two sets of changes because iOS 12 is weird and iOS 13 is starting to depart quite violently from the BSD sockets interface.

I'm pretty sure it won't cause regressions on the app level, but things to check:

* Make sure you still have a connection to the local webserver after you background the app and then foreground it again.
* Make sure you still have a connection to the local webserver when you restart the app _after_ starting it up and then shutting it down again as soon as the VPN connection is active.
* Check that any remote content you're loading is still coming in when the VPN is active. 

Also, two new undocumented functions (iOS only) that might be helpful:

`forge.live.reloadInitialPage();`

Forces the app's index.html to reload into the webview

`forge.live.restartServer();`

Forces the webserver to shut down and restart
