### ISSUE TITLE
Wrong permission request in the capture module on iOS

### ISSUE THREAD

**Issue by tomkretzschmar** [trigger-corp/forge#37]
When using `forge.capture.getImage(...)` and selecting the camera on iOS devices, two permission requests for both gallery (first request) and camera (second request) are shown. This leads to our apps being rejected from Apple since December 2019 with the message: 

> “Specifically, tapping “Camera” calls the photo gallery modal alert, which is not appropriate.“ 

**Device information:**
 - Hardware: iPhone X
 - Operating System and Version: all iOS versions
 - Forge Platform version: 2.8.5

**App information:**

`src/config.json`:
```
{
  "config_version": "4",
  "version": "...",
  "platform_version": "2.8.5",
  "core": {
    "general": {
      "logging": {
        "level": "INFO"
      },
      "reload": true,
      "trusted_urls": ["http://*/*","https://*/*"]

    },
    "ios": {
      "device_family": "any",
      "package_name": "...",
      "disable_web_storage_backup": true,
      "webview": "WKWebView"
    }
  },
  "flags": {
    "migrate_web_storage_for_webview": false,
    "move_filescheme_storage_to_httpscheme": false,
    "android_workaround_transparent_statusbar_keyboard_bug": true,
    "ios_also_set_css_safe_area_inset_env_as_var": true
  },
  "modules": {
    ...
    "file": {
      "version": "2.24",
      "config": {
        "usage_description": "Allow to upload images or videos stored on your device, e.g. for in app posts, comments or chat messages."
      },
      "disabled": %disable_file_module%
    },
    "capture": {
      "version": "2.25",
      "config": {
        "usage_description": "Allow to upload images or videos stored on your device, e.g. for in app posts, comments or chat messages."
      }
    },
    ...
    "prefs": {
      "version": "2.2",
      "config": {}
    },
    "browsersettings": {
      "version": "1.6",
      "config": {
        "accept_cookies": true,
        "media_playback": {
          "inline_video": false,
          "autoplay_video": true,
          "enable_html5_audio": true,
          "enable_background_audio": false,
          "respect_playing_audio": true
        }
      }
    },
    ...
  }
}

```

**To Reproduce**

1. Call `forge.capture.getImage({}, successFunc, errorFunc)` 
2. Select *Camera*
3. See permission request for gallery and camera (and accept)
4. Camera opens

or even do:

1. Call `forge.capture({source: 'camera'}, successFunc, errorFunc)``
2. See permission request for gallery and camera (and accept)
3. Camera opens
 
**Expected behaviour**
 
When selecting camera, you are prompted for giving access to the camera only.

**Actual behaviour**

When selecting camera, you are prompted for giving access to both the camera and the gallery.

**Comment by antoinevg** [comment]
This is due to a workaround for a horrible bug Apple introduced three years ago with iOS 11 as a consequence of `UIImagePickerControl` no longer running in-process. 

What happens is that the permission request when trying to save an image taken by the Camera to the Gallery now executes AFTER we receive the completion callback from the Camera. 

This, of course, means that any attempt to save the photo returned by the camera to the device gallery will fail because the user has not yet granted permissions to the gallery at the point where we receive the photo.

🤦🏼‍♂️

This mean we have to work around it by requesting Photo Gallery permissions **_before_** presenting the Camera. (i.e. https://github.com/trigger-corp/trigger.io-file/commit/41c6329dd4b14b5283afd78cc26755913ddad384)

So, some options are:

1. Try to educate the reviewer about the incompatibility between what they are asking for and how Apple have designed their API's. 
2. Try and change the `usage_description` description fields  to find something that lets the reviewer know what's going on. e.g. maybe for the `file` `usage_description` say something like _"we need access to your gallery in order to save the photo you're about to take"_  (`file.usage_description` is gallery, `capture.usage_description` is camera)
3. Use the [permissions module](https://trigger.io/modules/permissions/current/docs/index.html) to manually ask for permission to the device gallery at some point in the application flow before giving them the option to use the camera.

**Comment by tomkretzschmar** [comment]
Thanks for this insights. We'll try and change the description and convince our reviewers.
