### ISSUE TITLE
iOS builds not finishing

### ISSUE THREAD

**Issue by frrob** [trigger-corp/forge#96]
Hello @antoinevg ,

Since today we have the problem that we cannot build apps for iOS.
The forge command does not finish after it was running for 2h.
Is there a known problem?
Maybe a relationship to this case? #48
Thanks for your support!

**Comment by soemo** [comment]
Hello, can you give us some updates. Did you found out whats going on?

**Comment by antoinevg** [comment]
My deepest apologies, Apple would choose the one day I was away from the office to do a repeat of #48.

Everything is back up.

**Comment by frrob** [comment]
Hi @antoinevg ,
Today multiple of our colleagues are experiencing this problem again.
The service is working on and off again. 
Can you please check it out?

Thanks!

**Comment by antoinevg** [comment]
Hrrrmmm… services are up but I'm randomly seeing VERY slow speeds from Amazon S3 when the build process downloads the core build instructions.

Let me follow up with AWS and our hosting provider to see if there are any issues they're aware of.

**Comment by frrob** [comment]
Thank for taking care! 🙏

**Comment by antoinevg** [comment]
Ah haha…

Are all these builds against `v2.9.4` ?

If so, the problem is maybe not with our servers but the size of Google's `bundletool.jar` which forge needs to assemble the `.aab` files on the developer workstation during the packaging step.

It's 25 Megabytes (!) big which usually is not a problem because it only gets downloaded once and cached… 

But if you are making a lot of `src/config.json` changes or cleaning out the build directories between rebuilds… It means this file needs to be downloaded again every time!

You can check for this by trying to build against `v2.9.3` and seeing if it's just as slow.

Next week I'll look at some other way we can get `bundletool.jar` into the build system. Maybe bundle it with the command line tools instead.

In the meantime, the builds will complete - you'll just have to wait a little!

**Comment by frrob** [comment]
It is correct that we are currently testing `v2.9.4`, but we are building iOS only.
Should this still be related?

We try testing this with `v2.9.3`

**Comment by antoinevg** [comment]
I've pushed some changes to the behavior. Google's `bundletool.jar` only gets downloaded during the packaging step now and (as long as you don't delete your app's `.lib` directory) will survive full rebuilds.

Please let me know if this helps!
